### ISSUE TITLE
`/middleware/go/main.so` in the command line  vs `helloworld.so` in the api def

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/native-go-auth-middleware#1]
`/middleware/go/main.so` in the command line  vs `helloworld.so` in the api def

**Comment by sedkis** [comment]
nice eye @letzya

**Comment by sedkis** [comment]
fixed https://github.com/TykTechnologies/native-go-auth-middleware/commit/18d384f04589edbd77c39ad4d17532c06efc8b5c
